### ISSUE TITLE
同义词热更后所有同义词均会失效

### ISSUE THREAD

**Issue by sinhang** [bells/elasticsearch-analysis-dynamic-synonym#104]
重现方式：
1.启动后正常
2.新增同义词后所有同义词失效

如下：
更新前：
![image](https://user-images.githubusercontent.com/8141859/161368922-38696fd1-d3ec-4c2c-9ef5-0371ecd0346b.png)
新增同义词后：
![image](https://user-images.githubusercontent.com/8141859/161369068-5fe180c7-73af-4f31-823f-049709d3f763.png)

**Comment by sinhang** [comment]
es版本：
7.17.0

**Comment by sinhang** [comment]
使用接口后没有出现这个问题。

**Comment by terloo** [comment]
@sinhang 我也遇到这个问题了，太头疼了，能请教一下“使用接口”具体是指什么吗？
