### ISSUE TITLE
elasticsearch8以上不支持，一打包就报错啊啊啊啊啊

### ISSUE THREAD

**Issue by ColorfulDick** [bells/elasticsearch-analysis-dynamic-synonym#110]
![企业微信截图_16596898369394](https://user-images.githubusercontent.com/40350896/183041868-62a1255b-38c0-4f0d-9673-2619b6f5c41d.png)

**Comment by ColorfulDick** [comment]
我改成了8.2.3，打包失败；改回7.16.2，又正常了

**Comment by xuanyuanbao** [comment]
应该是依赖有问题，不能直接修改
