### ISSUE TITLE
master分支下载后编译失败

### ISSUE THREAD

**Issue by licdatgithub** [bells/elasticsearch-analysis-dynamic-synonym#115]
<img width="1828" alt="image" src="https://github.com/bells/elasticsearch-analysis-dynamic-synonym/assets/20736174/e844bfd7-be9b-4867-bf5b-7385188f57fd">

**Comment by licdatgithub** [comment]
问题解决，在gitee下载了tar.gz格式的包后 编译正常。 附链接：
https://gitcode.net/mirrors/bells/elasticsearch-analysis-dynamic-synonym?utm_source=csdn_github_accelerator

**Comment by licdatgithub** [comment]
版本7.4.2 改为7.6.2后，编译异常

**Comment by showlist** [comment]
![1686121309204](https://github.com/bells/elasticsearch-analysis-dynamic-synonym/assets/31266174/892c9b06-2186-437c-b638-5a8388932ce3)
所有的异常都在23年4月18号的提交导致，建议回退版本

**Comment by licdatgithub** [comment]
已经手动修改了，感谢你的回复

**Comment by licdatgithub** [comment]
改了下源码，问题已经解决了
