### ISSUE TITLE
编译至es8.12.2,create方法抛异常

### ISSUE THREAD

**Issue by Piupiudiu** [bells/elasticsearch-analysis-dynamic-synonym#121]
![image](https://github.com/bells/elasticsearch-analysis-dynamic-synonym/assets/88680353/81789f47-d2d2-487d-bbf1-32b7993bb00c)

**Comment by docjue** [comment]
我也遇到了，看源码是直接调用了create方法，但是不知道调用位置

**Comment by 562272115** [comment]
编译成功了么，大佬

**Comment by docjue** [comment]
没有，也在等官方更新版本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bells/elasticsearch-analysis-dynamic-synonym"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bells/elasticsearch-analysis-dynamic-synonym] 编译至es8.12.2,create方法抛异常 (Issue #121)





 
编译成功了么，大佬

**Comment by Piupiudiu** [comment]
这个方法少了@Override

**Comment by Piupiudiu** [comment]
这个方法少了Override注解
