### ISSUE TITLE
不重新索引或重启es集群如何生效？

### ISSUE THREAD

**Issue by weikuo0506** [bells/elasticsearch-analysis-dynamic-synonym#4]
请教下：目前动态词库可以加载，但是按照我的理解，必须把文档重新索引；或者重启es集群才能生效吧？

**Comment by bells** [comment]
@weikuo0506 这要看你是在什么时候使用同义词过滤器的，是在索引(index_analyzer)期间，还是在查询(search_analyzer)期间,或者两者同时使用。 如果在索引期间使用同义词，在同义词规则更改后，需要重新索引数据，这是因为新的规则需要重新应用到所有文档，如果在查询时使用同义词
，在同义词规则更改后，会立刻看到效果。

**Comment by diaochengkun** [comment]
不好意思，对elasticsearch不是很熟悉,如何配置在查询(search_analyzer)期间使用同义词过滤器

**Comment by diaochengkun** [comment]
我现在是这样配置的      
   "name":{
          "type": "text",
          "search_analyzer": "ik_max_word",
          "analyzer": "ik_max_word"
        }
  "settings": {
    "analysis": {
      "filter": {
        "local_synonym" : {
            "type" : "dynamic_synonym",
            "synonyms_path" : "synonyms.txt"  
        }
      },
      "analyzer": {
        "ik_max_word": {
          "type": "custom",
          "tokenizer": "ik_max_word",
          "filter": [
              "local_synonym"
           ]
        },
        "ik-smart": {
          "type": "custom",
          "tokenizer": "ik_smart",
          "filter": [
              "local_synonym"
           ]
        }
      }
    }
  }

**Comment by bells** [comment]
search_analyzer就用这个指定 自定义的分词器就行。。分词器的名字不要用这个吧：ik_max_word
换一个。然后这个自定义的分词器里面定义filter就行，

diaochengkun <notifications@github.com> 于2018年10月9日周二 下午6:36写道：
