### ISSUE TITLE
是否需要重启index

### ISSUE THREAD

**Issue by Vincent717** [bells/elasticsearch-analysis-dynamic-synonym#6]
Hi,
今天一直在考虑更新了同义词字典之后，es没法重新加载的问题。后来发现只要将index close了再open就可以了。
当然也看到了你的插件，正在看源码，写得很清晰而且注释很完备！
不过想问一个问题，不知道你的插件的原理是什么呢？是我上面说的，在检测到synonym的file有更新之后，就将index关闭再开启吗？
以及感觉你的插件和https://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym 这个插件功能上有点类似是吗？
谢谢！

**Comment by bells** [comment]
更新了同义词词库，如果你在索引阶段用到了，则需要重新建立索引。和这个插件elasticsearch-analysis-file-watcher-synonym功能类似，并参考了它。

**Comment by sinhang** [comment]
https://github.com/bells/elasticsearch-analysis-dynamic-synonym/issues/105  这个也是一样的吗？
