### ISSUE TITLE
支持6.4.3

### ISSUE THREAD

**Issue by TerryLam2010** [bells/elasticsearch-analysis-dynamic-synonym#66]
RT. 想支持6.4.3, 改了pom之后发现AnalysisMode 并没有。
你的代码没有打版本分支，不好还原。有什么好的解决办法吗？

**Comment by TerryLam2010** [comment]
已经自己解决。

**Comment by mukulGoelTokopedia** [comment]
How did it get solved? I want for 6.8.8
